<?php
/***************************************************************************
 *  					Theme Functions
 * 	----------------------------------------------------------------------
 * 						DO NOT EDIT THIS FILE
 *	----------------------------------------------------------------------
 *
 *  					Copyright (C) Themify
 * 						https://themify.me
 *
 *  To add custom PHP functions to the theme, create a child theme (https://themify.me/docs/child-theme) and add it to the child theme functions.php file.
 *  They will be added to the theme automatically.
 *
 ***************************************************************************/

/** Compatibility with portfolio posts plugin */
const THEMIFY_PORTFOLIO_POSTS_COMPAT_MODE=true;
/////// Actions ////////
// Init post, page and additional post types if they exist
add_action( 'after_setup_theme', 'themify_theme_after_setup_theme' );



// Exclude CPT for sidebar
add_filter( 'themify_exclude_CPT_for_sidebar', 'themify_CPT_exclude_sidebar' );

// Add theme specific classes in body tag
add_filter( 'body_class', 'themify_theme_body_class' );

add_action( 'wp_footer', 'themify_theme_split_loader_in_builder_layout_page' );



Themify_Enqueue_Assets::$mediaMaxWidth=false;

function themify_theme_enqueue_footer(){
	// Get theme version for Themify theme scripts and styles
	$theme_version = Themify_Enqueue_Assets::$themeVersion;
	// Check split scroll & disable it on mobile and customizer
	$split_scroll = themify_theme_is_fullpage_scroll();

	// Prepare JS variables
	$themify_script_vars = array(
		'sticky_header'=>themify_theme_sticky_logo(),
		'pageLoaderEffect'=>themify_theme_has_page_loader()
	);
	// One Page Scroll
	if ( $split_scroll!==false ) {
	    Themify_Enqueue_Assets::loadThemeStyleModule( 'split',null,true);
	    if($split_scroll===true){
		    $themify_script_vars['splitScrollThreshold']=680;
		    $splitVer='0.2.3';
		    $themify_script_vars['s_p_v']=$splitVer;
		    Themify_Enqueue_Assets::addPrefetchJs(THEME_URI . '/js/modules/split/split.js',$theme_version);
		    Themify_Enqueue_Assets::addPrefetchJs(THEME_URI . '/js/modules/split/splitscroll.min.js',$splitVer);
	    }
	}
	else{
		$themify_script_vars['infinityEnabled']=(is_home() || is_archive() || themify_is_query_page() || is_search())?1:0;
		
		if($themify_script_vars['infinityEnabled']===1){
			$themify_script_vars['autoInfinite']=themify_check( 'setting-autoinfinite',true ) ? 'no': 'auto';
			$themify_script_vars['infiniteURL']=!themify_check( 'setting-infinite-url',true ) ? 1 :'';
		}
	}

	if(is_single() || is_singular('portfolio')){
		Themify_Enqueue_Assets::loadThemeStyleModule('single/single');
                if(is_single('post')){
                    Themify_Enqueue_Assets::loadThemeStyleModule('single/single-'.get_post_type());
                }
	}
	// Pass variable values to JavaScript
	wp_localize_script( 'themify-main-script', 'themifyScript', apply_filters( 'themify_script_vars', $themify_script_vars ) );

}
add_action( 'comment_form_before', 'themify_comment_form_css' );
function themify_comment_form_css(){
	remove_action( 'comment_form_before', 'themify_comment_form_css' );
	Themify_Enqueue_Assets::loadThemeStyleModule('comments');
}
add_action( 'pre_get_search_form', 'themify_theme_search_form_css' );
function themify_theme_search_form_css(){
    remove_action( 'pre_get_search_form', 'themify_theme_search_form_css' );
    Themify_Enqueue_Assets::loadThemeStyleModule('search-form');
}
/**
 * Load Google fonts used by the theme
 *
 * @return array
 */
function themify_theme_google_fonts( $fonts ) {
	/* translators: If there are characters in your language that are not supported by Montserrat, translate this to 'off'. Do not translate into your own language. */
	if ( 'off' !== _x( 'on', 'Montserrat font: on or off', 'themify' ) ) {
		$fonts['montserrat'] = 'Montserrat:400,700';
	}
	/* translators: If there are characters in your language that are not supported by Roboto Slab, translate this to 'off'. Do not translate into your own language. */
	if ( 'off' !== _x( 'on', 'Roboto Slab font: on or off', 'themify' ) ) {
		$fonts['roboto-slab'] = 'Roboto+Slab:700,400';
	}
	/* translators: If there are characters in your language that are not supported by Sorts Mill Goudy, translate this to 'off'. Do not translate into your own language. */
	if ( 'off' !== _x( 'on', 'Sorts Mill Goudy font: on or off', 'themify' ) ) {
		$fonts['sorts-mill-goudy'] = 'Sorts+Mill+Goudy:400,400i';
	}

	return $fonts;
}
add_filter( 'themify_google_fonts', 'themify_theme_google_fonts' );

/**
 * Set the fixed-header selector for the scroll highlight script
 *
 * @since 1.0.0
 */
function themify_theme_scroll_highlight_vars( $vars ) {
    if(themify_theme_is_fullpage_scroll()){
	$vars['scroll']='external';
    }
    return $vars;
}
add_filter( 'themify_builder_scroll_highlight_vars', 'themify_theme_scroll_highlight_vars' );


if ( ! function_exists( 'themify_theme_after_setup_theme' ) ) {
	/**
	 * Register theme support.
	 *
	 * Initialize custom panel with its definitions.
	 * Custom panel definitions are located in admin/post-type-TYPE.php
	 *
	 * @since 1.0.7
	 */
	function themify_theme_after_setup_theme() {
		// Enable WordPress feature image
		add_theme_support( 'post-thumbnails' );
		$supportedCss=array(
		    'grid2-thumb',
		    'grid2',
		    'grid3',
		    'grid4',
		    'list-large-image',
		    'list-post',
		    'list-thumb-image',
		    'widget_recent-posts',
		    'widget_text',
		    'widget_themify-feature-posts',
		    'widget_themify-flickr',
		    'widget_themify-social-links',
		    'comments',
		    'post-filter'
		);
		foreach ($supportedCss as $css){
		    Themify_Enqueue_Assets::add_theme_support_css($css);
		}
		if(themify_is_woocommerce_active()){
		    //add wc css 
		    Themify_Enqueue_Assets::add_theme_support_css( 'wc' );
		    $supportedCss=array('wc_cart','wc_checkout');
		    foreach ($supportedCss as $css){
			Themify_Enqueue_Assets::add_theme_support_css($css);
		    }
		}
		unset($supportedCss);
		// Load required files for post, page and custom post types where it applies
		foreach ( array('portfolio', 'product' ) as $type ) {
			require_once( THEME_DIR."/admin/post-type-$type.php" );
		}
		register_nav_menus( array(
			'main-nav' => __( 'Main Navigation', 'themify' ),
			'footer-nav' => __( 'Footer Navigation', 'themify' ),
		));
	}
}

if ( ! function_exists( 'themify_theme_has_submenu' ) ) {
	/**
	 * Sets custom class if menu item has a submenu.
	 *
	 * @since 1.0.0
	 *
	 * @param array $sorted_menu_items The menu items to filter.
	 *
	 * @return array The filtered menu items.
	 */
	function themify_theme_has_submenu( $sorted_menu_items ) {
		$last_top = 0;
		foreach ( $sorted_menu_items as $key => $obj ) {
			if ( 0 == $obj->menu_item_parent ) {
				$last_top = $key;
			} else {
				if ( isset( $sorted_menu_items[$last_top] ) ) {
					$sorted_menu_items[$last_top]->classes['has-sub-menu'] = 'has-sub-menu';
				}
			}
		}
		return $sorted_menu_items;
	}
	add_filter( 'wp_nav_menu_objects', 'themify_theme_has_submenu', 10 );
}

if( ! function_exists('themify_CPT_exclude_sidebar') ) {
	/**
	 * Exclude Custom Post Types
	 */
	function themify_CPT_exclude_sidebar($CPT = array()) {
		$CPT[] = 'portfolio';
		return $CPT;
	}
}

/**
 * Output required classes like transition setting, builder row scrolling setting.
 * In single views, check if there's a video and add class accordingly.
 *
 * @since 1.0.0
 *
 * @param array $classes
 *
 * @return array
 */
function themify_theme_body_class( $classes ) {
	global $themify;
	$splitScroll=themify_theme_is_fullpage_scroll();
	if($splitScroll!==false){
        add_filter( 'themify_builder_row_attributes', 'themify_theme_disable_row_animation', 10, 3 );
		$classes[] = 'full-section-scrolling';
		if($splitScroll===true){
			$classes[] = !themify_is_touch( 'phone' )?'split-scroll tf_lazy_disable':'split-scroll-off';
		}
	}
	else{
		$classes[] = 'split-scroll-off';
	}
	
	if ( is_single() && '' != themify_get( 'video_url' ) ) {
		$classes[] = 'has-video';
	}
	$classes[] =$splitScroll!=='builderActive' && themify_theme_has_page_loader()?'hidden-view':'ready-view';

	// Header Design
	$header = themify_area_design( 'header' );
	$classes[] = 'none' === $header ? 'header-none' : $header;

	if ( ( is_singular() || themify_is_shop() ) && 'transparent' === themify_get( 'header_wrap' ) ) {
		Themify_Enqueue_Assets::loadThemeStyleModule('transparent-header');
		$classes[] = 'transparent-header';
	}

	if( 'none' !== $header && themify_theme_fixed_header() ) {
		$classes[] = 'fixed-header-enabled';
	}
	if($themify->layout === 'sidebar-none'){
		Themify_Enqueue_Assets::loadThemeStyleModule('sidebar-none');
	}

	return $classes;
}


if ( ! function_exists( 'themify_theme_show_area' ) ) {
	/**
	 * Checks whether to show a certain layout area or not.
	 *
	 * @param string $area
	 *
	 * @return bool
	 */
	function themify_theme_show_area( $area = '' ) {
		if ( 'header' === $area ) {
			return 'none' === themify_area_design( 'header' ) ? false : true;
		} else {
			if ( ( is_singular() || is_post_type_archive( 'product' ) ) && ! is_attachment() ) {
				$exclude = themify_get( 'exclude_' . $area );
				if ( 'yes' === $exclude ) {
					return false;
				} elseif ( 'no' === $exclude ) {
					return true;
				} else {
					return !themify_check( 'setting-exclude_' . $area,true );
				}
			} elseif ( themify_check( 'setting-exclude_' . $area,true ) ) {
				return false;
			}
		}

		return true;
	}
}

if ( ! function_exists( 'themify_theme_do_not_exclude_all' ) ) {
	/**
	 * Checks if all the elements in a certain area have been excluded.
	 *
	 * @param string $area
	 *
	 * @return bool
	 */
	function themify_theme_do_not_exclude_all( $area = 'header' ) {
		if ( 'mobile-menu' === $area ) {
			return themify_theme_show_area( 'search_form' ) || themify_theme_show_area( 'social_widget' ) || themify_theme_show_area( 'rss' ) || themify_theme_show_area( 'menu_navigation' );
		} elseif ( 'header' === $area ) {
			return themify_theme_show_area( 'site_logo' ) || themify_theme_show_area( 'site_tagline' ) || themify_theme_show_area( 'search_form' ) || themify_theme_show_area( 'social_widget' ) || themify_theme_show_area( 'rss' ) || themify_theme_show_area( 'menu_navigation' );
		}
		return false;
	}
}

if ( ! function_exists( 'themify_theme_custom_post_css' ) ) {
	/**
	 * Outputs custom post CSS at the end of a post
	 * @since 1.0.0
	 */
	function themify_theme_custom_post_css() {
		global $themify;
		if ( in_array( get_post_type(), array( 'post', 'page', 'portfolio', 'product' ) ) || themify_is_shop() ) {
			$post_id = $themify->page_id;
			if ( is_page() ) {
				$entry_id = '.page-id-' . $post_id;
			} elseif( themify_is_shop() ) {
					$entry_id = '.post-type-archive-product';
			} else {
				$entry_id = '.postid-' . $post_id;
			}
			$headerwrap = $entry_id . ' #headerwrap';
			$site_logo = $entry_id . ' #site-logo';
			$site_description = $entry_id . ' #site-description';
			$main_nav = $entry_id . ' #main-nav';
			$social_widget = $entry_id . ' .social-widget';
			$css = array();
			$style = '';
			$rules = array();

			if ( 'transparent' != themify_get( 'header_wrap' ) ) {
				$rules = array(
					$headerwrap => array(
						array(
							'prop' => 'background-color',
							'key'  => 'background_color'
						),
						array(
							'prop' => 'background-image',
							'key'  => 'background_image'
						),
						array(
							'prop' => 'background-repeat',
							'key'  => 'background_repeat',
							'dependson' => array(
								'prop' => 'background-image',
								'key'  => 'background_image'
							),
						),
					),
					"$entry_id #site-logo span:after, $entry_id #headerwrap #searchform, $entry_id #main-nav .current_page_item a, $entry_id #main-nav .current-menu-item a" => array(
							array(
								'prop' => 'border-color',
								'key'  => 'headerwrap_text_color'
							),
					),
				);
			}

			$rules["$headerwrap, $site_logo, $site_description"] = array(
				array(
					'prop' => 'color',
					'key'  => 'headerwrap_text_color'
				),
			);

			$rules["$site_logo a, $site_description a, $social_widget a, $main_nav > li > a"] = array(
				array(
					'prop' => 'color',
					'key'  => 'headerwrap_link_color'
				),
			);

			foreach ( $rules as $selector => $property ) {
				foreach ( $property as $val ) {
					$prop = $val['prop'];
					$key = $val['key'];
					if ( is_array( $key ) ) {
						if ( $prop == 'font-size' && ( $key_zero = themify_get( $key[0] ) ) ) {
							$css[$selector][$prop] = $prop . ': ' . $key_zero . themify_get( $key[1] );
						}
					} elseif ( ( $plain_key = themify_get( $key ) ) && 'default' != $plain_key ) {
						if ( $prop == 'color' || stripos( $prop, 'color' ) ) {
							$css[$selector][$prop] = $prop . ': ' . themify_get_color( $key );
						}
						elseif ( $prop == 'background-image' && 'default' != $plain_key ) {
							$css[$selector][$prop] = $prop .': url(' . $plain_key . ')';
						}
						elseif ( $prop == 'background-repeat' && 'fullcover' == $plain_key ) {
							if ( isset( $val['dependson'] ) ) {
								if ( $val['dependson']['prop'] == 'background-image' && ( 'default' != themify_get( $val['dependson']['key'] ) ) ) {
									$css[$selector]['background-size'] = 'background-size: cover';
								}
							} else {
								$css[$selector]['background-size'] = 'background-size: cover';
							}
						}
						elseif ( $prop == 'font-family' ) {
							$font = $plain_key;
							$css[$selector][$prop] = $prop .': '. $font;
							if ( ! in_array( $font, themify_get_web_safe_font_list( true ) ) ) {
								$themify->google_fonts .= str_replace( ' ', '+', $font.'|' );
							}
						}
						else {
							$css[$selector][$prop] = $prop .': '. $plain_key;
						}
					}
				}
				if ( ! empty( $css[$selector] ) ) {
					$style .= "$selector {\n\t" . implode( ";\n\t", $css[$selector] ) . "\n}\n";
				}
			}

			if ( '' != $style ) {
				echo "\n<!-- Entry Style -->\n<style>\n$style</style>\n<!-- End Entry Style -->\n";
			}
		}
	}
	add_action( 'wp_head', 'themify_theme_custom_post_css', 77 );
}

if ( ! function_exists( 'themify_theme_featured_area_style' ) ) {
	/**
	 * Returns the background repeat style as a class.
	 *
	 * @return mixed|string
	 */
	function themify_theme_featured_area_style() {
		return themify_check( 'background_repeat' ) ? themify_get( 'background_repeat' ) : '';
	}
}

/**
 * Adds page loading animation
 *
 * @since 1.0.0
 */
function themify_theme_add_split_loader() {
	if ( themify_theme_has_page_loader() ) :
            $color = themify_get_color('setting-page_loader_color',false,true);
            $icon = themify_get('setting-page_loader_icon',false,true);
            $cl = $bg = '';
            if($icon){
                // check if the value is a valid icon name
                $cl = themify_get_icon( $icon );
                // not an icon, it's an image
                if ( empty( $cl ) ) {
                    $cl='';
                    $bg = 'background:transparent url(' . $icon . ') center/cover no-repeat';
                }else{
                    $bg = 'background:0';
                }
            }
		Themify_Enqueue_Assets::loadThemeStyleModule('split-loader');
	?>
        <?php if($color || $bg):?>
        <style>
            <?php if($color):?>.split-loader,.hidden-view,body .split-panel{background-color:<?php echo $color ?>}<?php endif;?>
            <?php if($bg):?>.split-loader .split-spinner{<?php echo $bg ?>}<?php endif;?>
        </style>
    <?php endif;?>
	<?php if(themify_theme_is_fullpage_scroll()===true):?>
		<div class="split-panel split-right tf_h"></div>
		<div class="split-panel split-left tf_h"></div>
	<?php endif;?>
	<div class="split-loader tf_w tf_h tf_textc">
		<div class="split-spinner tf_rel"><?php echo $cl?></div>
	</div>
	<?php
	endif;
}

/**
 * Hook split loader to builder layout and layout part single page.
 * @since 1.1.7
 */
function themify_theme_split_loader_in_builder_layout_page() {
	if ( is_singular( array( 'tbuilder_layout', 'tbuilder_layout_part' ) ) ) {
		themify_theme_add_split_loader();
	}
}

/**
 * Checks if current page has split scroll.
 *
 * @since 1.0.0
 *
 * @return bool
 */
function themify_theme_is_fullpage_scroll() {
    static $is = NULL;
    if($is===null){
        $is = apply_filters( 'themify_theme_has_split_scroll', ( is_search() || !is_page() || ( isset( $_REQUEST['wp_customize'] ) && 'on' === $_REQUEST['wp_customize'] ) || ( is_admin() && 'customize.php' === basename( $_SERVER['PHP_SELF'] ) ) ) ? false : (is_page() && 'yes' === themify_get( 'split_scroll' )) );
	}
    return $is;
}

/**
 * Checks if current page has page loader effect.
 *
 * @since 1.0.0
 *
 * @return bool
 */
function themify_theme_has_page_loader() {
	$isSplit=themify_theme_is_fullpage_scroll();
    return $isSplit===true?true:($isSplit===false && 'on' !== themify_get( 'setting-page_loader_disabled',false,true ));
}



/**
 * Set portfolio post type slug
 *
 * @since 1.0.0
 *
 * @return string
 */
function themify_theme_portfolio_post_rewrite($slugs) {
	$slug = themify_get( 'themify_portfolio_slug','',true );
    if(is_array($slugs)){
        $slugs['post'] = empty( $slug ) ? apply_filters( 'themify_portfolio_rewrite', $slugs['post'] ) : $slug;
		$category_slug = themify_get( 'themify_portfolio_category_slug','',true );
		$slugs['tax'] = empty( $category_slug ) ? apply_filters( 'themify_portfolio_category_rewrite', $slugs['tax'] ) : $category_slug;    
    }else{
		$slugs = empty( $slug ) ? apply_filters( 'themify_portfolio_rewrite', 'project' ) : $slug;
    }
	return $slugs;
}
add_filter( 'themify_portfolio_post_rewrite', 'themify_theme_portfolio_post_rewrite' );

if ( ! function_exists( 'themify_theme_entry_title_tag' ) ) {
	/**
	 * Displays the entry title tag, outputting h1 for singular views and h2 otherwise.
	 * @Deprecated
	 *
	 * @since 1.0.0
	 *
	 * @return string
	 */
	function themify_theme_entry_title_tag( $echo = true ) {
		global $themify;
		$tag = is_singular() && empty($themify->is_shortcode) ? 'h1' : 'h2';
		$tag = apply_filters( 'themify_entry_title_tag', $tag );
		if( ! $echo )
			return $tag;
		echo $tag;
	}
}

function themify_theme_fixed_header() {
        static $is = NULL;
        if($is===null){
            if ( is_singular( array( 'post', 'page', 'portfolio' ) ) ) {
                    $fixed_header_field = themify_get( 'fixed_header' );
                    if ( 'yes' === $fixed_header_field ) {
                        $is = 'fixed-header';
                        return $is;
                    } elseif ( 'no' === $fixed_header_field ) {
                            $is = '';
                            return $is;
                    }
            }
            $is = themify_check( 'setting-fixed_header_disabled',true ) ? '' : 'fixed-header';
        }
        return $is;
}

function themify_theme_sticky_logo(){
     if(themify_theme_fixed_header()){
        global $themify_customizer;
        $logo = json_decode($themify_customizer->get_cached_mod('sticky_header_imageselect'));
        return !empty($logo->src)?$logo:false;
     }
     else{
         return false;
     }
}

/**
 * Additional classes for post and portfolio builder
 */
add_filter( 'themify_builder_module_loops_wrapper', 'themify_add_builder_classes', 10, 3 );
function themify_add_builder_classes($classes,$mod,$slug){

	if(isset($mod['layout_' . $slug] ) &&( $slug === 'post' || $slug === 'portfolio' ) ) {

		$is_portfolio = $slug === 'portfolio';
		$layout = $mod['layout_' . $slug];
		$masonry = $gutter = $content_layout = false;
		$content_layout = !empty($mod[$slug . '_content_layout'])
		&& $mod[$slug.'_content_layout'] !== 'no'
		&& ! in_array( $layout, array('list-large-image', 'list-thumb-image','grid2-thumb') )
			? $mod[$slug . '_content_layout'] : false;

		if( $content_layout === 'default' ) {
			$content_layout = themify_get( 'setting-' . $slug . '_content_layout','',true );
		}

		$gutter = ! empty( $mod[$slug . '_gutter'] )
		&& ! in_array( $layout
			, array(
				'list-post',
				'list-large-image',
				'list-thumb-image',
				'grid2-thumb',
				'slider',
				'fullwidth'
			),true ) ? $mod[$slug . '_gutter'] : false;

		if( $gutter === 'default' ) {
			$gutter = themify_get( 'setting-' . $slug . '_gutter',false,true);
		}

		$masonry = ( ! empty( $mod['disable_masonry'] )
			&& $mod['disable_masonry'] !== 'no'
			&& ! in_array( $layout
				, array(
					'list-post',
					'fullwidth',
					'auto_tiles',
					'list-large-image',
					'list-thumb-image',
					'grid2-thumb',
					'slider'
				),true ) ) ? 'masonry' : false;
		if( $masonry && $mod['disable_masonry'] === 'default' ) {
			$masonry = $is_portfolio
				? themify_get( 'setting-portfolio_disable_masonry',false,true )
				: themify_get( 'setting-disable_masonry',false,true );
			$masonry = $masonry === 'yes' ? 'masonry' : false;
		}

		if( $content_layout ) {
			$classes.=' '.$content_layout;
		}

		if( $gutter ) {
			$classes.=' '.$gutter;
		}

		if( $masonry ) {
			$classes.=' '.$masonry;
		}

	}
	return $classes;
}

function themify_theme_container_props($args,$post_type,$layout){
    if($layout!=='list-post' && $layout!=='list-thumb-image' && $layout!=='list-large-image' ){
	if($post_type==='product'){
	    if('no' !== themify_get( 'setting-product_disable_masonry',false,true )){
		$args['class'][]='masonry';
		$args['data-layout']='packery';
	    }
	}
	else{
	    $masonry = $post_type==='portfolio'? themify_get( 'setting-portfolio_disable_masonry',false,true ): themify_get( 'setting-disable_masonry',false,true );
	    if($masonry==='yes'){
		$args['class'][]='masonry';
	    }
	}
    }
    return $args;
}
add_filter('themify_container_props','themify_theme_container_props',10,3);

/**
 * Disable row animation effects on split scroll
 *
 * @return 	array
 */
function themify_theme_disable_row_animation( $attr, $settings, $builder_id ) {
    if ( $builder_id === get_queried_object_id() ) {
        unset( $attr['data-sticky-active'], $attr['data-lax'], $attr['data-lax-anchor'], $attr['data-lax-optimize'], $attr['data-lax-no-op'] );
    }
    return $attr;
}
/*Let the builder know that page is full section enabled*/
function themify_theme_builder_full_section($vars) {
    if(themify_theme_is_fullpage_scroll()) {
        $vars['is_fullSection']=true;
    }
    return $vars;
}
add_filter('themify_builder_active_vars','themify_theme_builder_full_section',10,1);